import { FaStore } from "react-icons/fa";
import { v4 as uuid } from "uuid";

export const sidebarNavigationsMedia = [
    {
        id: uuid(),
        icon: FaStore,
        label: "Media",
        slug: "media",
        href: "/media",
        hrefMethod: () => router.push("/media"),
        active: false,
        show: true,
        children: [
            {
                id: uuid(),
                icon: FaStore,
                label: "All Medias",
                slug: "media-index",
                href: "/media",
                hrefMethod: () => router.push("/media"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
            {
                id: uuid(),
                icon: FaStore,
                label: "Create Media",
                slug: "media-create",
                href: "/media/create",
                hrefMethod: () => router.push("/media/create"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
            {
                id: uuid(),
                icon: FaStore,
                label: "Edit Media",
                slug: "media-edit",
                href: "/media/edit",
                hrefMethod: () => router.push("/media/edit"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
            {
                id: uuid(),
                icon: FaStore,
                label: "Delete Product",
                slug: "media-delete",
                href: "/media/delete",
                hrefMethod: () => router.push("/media/delete"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
        ],
        method: null,
    },
];
