import { FaStore } from "react-icons/fa";
import { v4 as uuid } from "uuid";

export const sidebarNavigationsMembers = [
    {
        id: uuid(),
        icon: FaStore,
        label: "Member",
        slug: "members",
        href: "/members",
        hrefMethod: () => router.push("/members"),
        active: false,
        show: true,
        children: [
            {
                id: uuid(),
                icon: FaStore,
                label: "All Members",
                slug: "members-index",
                href: "/members",
                hrefMethod: () => router.push("/members"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
            {
                id: uuid(),
                icon: FaStore,
                label: "Me",
                slug: "members-me",
                href: "/members/create",
                hrefMethod: () => router.push("/members/me"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
            {
                id: uuid(),
                icon: FaStore,
                label: "Create Member",
                slug: "members-create",
                href: "/members/create",
                hrefMethod: () => router.push("/members/create"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
            {
                id: uuid(),
                icon: FaStore,
                label: "Edit Member",
                slug: "members-edit",
                href: "/members/edit",
                hrefMethod: () => router.push("/members/edit"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
            {
                id: uuid(),
                icon: FaStore,
                label: "Delete Member",
                slug: "members-delete",
                href: "/members/delete",
                hrefMethod: () => router.push("/members/delete"),
                active: false,
                show: true,
                children: [],
                method: null,
            },
        ],
        method: null,
    },
];
